### ISSUE TITLE
Duplicate help tag g:echodoc#type

### ISSUE THREAD

**Issue by Coacher** [Shougo/echodoc.vim#101]
Hello.

1f27db04dd27b53146e77dc23721e9343621de32 introduced duplicate tags `g:echodoc#type` on lines 93 and 124 in `doc/echodoc.txt`. Vim fails to create help tags. The latter should be `g:echodoc#floating_config`. Probably too minor to create PR.

**Comment by Shougo** [comment]
Fixed.
