### ISSUE TITLE
Disable echodoc for specific filetype

### ISSUE THREAD

**Issue by petobens** [Shougo/echodoc.vim#11]
Is it possible to disable echodoc for a specific filetype or a list of filetypes?
If it is not possible, can you add the feature? Thanks!

**Comment by Shougo** [comment]
Why this feature is needed?
echodoc conflicts the other plugins?

**Comment by Shougo** [comment]
You can use `echodoc#disable()`, `echodoc#enable()`, `echodoc#is_enabled()` for it.

**Comment by petobens** [comment]
I want to disable echodoc for `tex` and `bib` filetypes. 
Consider the followinig minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/OneDrive/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/neocomplete/
set runtimepath+=$DOTVIM/bundle/echodoc/
set runtimepath+=$DOTVIM/bundle/vimtex/
filetype plugin indent on

let g:neocomplete#enable_at_startup = 1
if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
endif
let g:neocomplete#force_omni_input_patterns.tex =
        \ '\v\\\a*cite\a*([^]]*\])?\{(|[^}]*,)'
let g:echodoc_enable_at_startup = 1
```
Now (as in the GIF) do the following:

i) edit a `foo.tex` file that contains

```tex
\documentclass{article}
\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}
\begin{document}

\end{document}
```

ii) run `:call vimtex#init()` (to enable vimtex plugin omnicompletion)
iii) write `\cite{` and select one candidate (for example `Gaonkar`)
iv) In a new line  start typing: you will see that echodoc show the documentation for the bib-completion. I don't want to see this. Therefore I want to disable echodoc when dealing with `tex` and `bib` files.

Should I write an autocommand? How can I do it? Thanks in advance.


![blahhh](https://cloud.githubusercontent.com/assets/2583971/12040512/5bc4d572-ae48-11e5-9061-515b9a97d08a.gif)

**Comment by Shougo** [comment]
> Should I write an autocommand? How can I do it? Thanks in advance.

Yes.

```vim
autocmd FileType * call s:disable_echodoc()

function s:disable_echodoc() abort
  if &filetype ==# 'bib' || &filetype ==# 'tex'
    call echodoc#disable()
  else
    call echodoc#enable()
  endif
endfunction
```

**Comment by petobens** [comment]
Thank you!
