### ISSUE TITLE
How to make it to work with deoplete?

### ISSUE THREAD

**Issue by tex** [Shougo/echodoc.vim#17]
Hi Shougo,

I'm using deoplete, but it doesn't seem to trigger echodoc to show doc.

Deoplete provides a list of candidates, I select a one, then enter '('   (its with C++) and nothing happens. I expect that echodoc shows signature of function.

If I press `<C-X><C-N><Esc>` signature is shown.

How to make it to show signature when I write '(' ?

Thanks,
Milan

**Comment by Shougo** [comment]
Hm.  I will check it.
But I have not ESP skills.
Please create minimal init.vim less than 50 lines and reproduce ways from neovim starting.

**Comment by tex** [comment]
My config contained:
    set cmdheight=2
With this, echodoc does work as described in my issue report.

When this is used:
    set noshowmode
echodoc does work correctly.

**Comment by tex** [comment]
NVIM v0.1.6-294-gf96dfae
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/milan/.cache/pacaur/neovim-git/src/neovim-git/build/config -I/home/milan/.cache/pacaur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/milan/.cache/pacaur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/milan/.cache/pacaur/neovim-git/src/neovim-git/build/include
přeložil  milan@msvobod

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   systémový vimrc soubor: "$VIM/sysinit.vim"
  implicitní hodnota $VIM:"/usr/share/nvim"

**Comment by Shougo** [comment]
> Please create minimal init.vim less than 50 lines and reproduce ways from neovim starting.

Your uploaded information is not my desired one.

Please upload the information like this.
https://github.com/Shougo/deoplete.nvim/issues/320

I will close the issue if you don't upload the information.
This is MUST.

**Comment by Shougo** [comment]
The minimal init.vim must be executable using `nvim -u init.vim`.

My question:  Can other people reproduce the issue only using your information without ESP skills?

**Comment by tex** [comment]
```
set nocompatible
filetype plugin indent on
syntax enable

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source ~/.vimrc
endif


call plug#begin('~/.vim/plugged')

    Plug 'https://github.com/Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
        let g:deoplete#enable_at_startup = 1

    Plug 'https://github.com/zchee/deoplete-clang'            " C/C++ completion
        " libclang shared library path
        let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'

        " clang builtin header path
        let g:deoplete#sources#clang#clang_header = '/usr/lib/clang/3.8.1/include'

        " C or C++ standard version
        let g:deoplete#sources#clang#std#c = 'c11'
        " or c++
        let g:deoplete#sources#clang#std#cpp = 'c++1z'

        " alphabetical sort order
        let g:deoplete#sources#clang#sort_algo = 'alphabetical'

        " compile_commands.json directory path
        let g:deoplete#sources#clang#clang_complete_database = '~/.cache/deoplete-clang/build/'

        " default flags
        let g:deoplete#sources#clang#flags = [ "-cc1", "-triple x86_64-unknown-linux-gnu", "-E", "-disable-free", "-disable-llvm-verifier", "-main-file-name", "-mrelocation-model static", "-mthread-model posix", "-mdisable-fp-elim", "-fmath-errno", "-masm-verbose", "-mconstructor-aliases", "-munwind-tables", "-fuse-init-array", "-target-cpu x86-64", "-v", "-dwarf-column-info", "-debugger-tuning=gdb", "-resource-dir /usr/bin/../lib/clang/3.8.1", "-internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1", "-internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1/x86_64-pc-linux-gnu", "-internal-isystem /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../include/c++/6.2.1/backward", "-internal-isystem /usr/local/include", "-internal-isystem /usr/bin/../lib/clang/3.8.1/include", "-internal-externc-isystem /include", "-internal-externc-isystem /usr/include", "-fdeprecated-macro", "-fdebug-compilation-dir ~/.cache/deoplete/build/", "-ferror-limit 19", "-fmessage-length 176", "-fobjc-runtime=gcc", "-fcxx-exceptions", "-fexceptions", "-fdiagnostics-show-option", "-fcolor-diagnostics", "-o", "-", "-x c++" ]

"Plug 'https://github.com/Shougo/context_filetype.vim.git'
Plug 'https://github.com/Shougo/echodoc.vim.git'
"   set cmdheight=2    " DOES NOT WORK
    set noshowmode    " DOES WORK
    let g:echodoc_enable_at_startup = 1

call plug#end()

    " deoplete needs to call this after plug#end()
    silent call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
```

**Comment by Shougo** [comment]
The minimal vimrc is OK.
Please upload the reproduce ways from neovim starting.
I cannot reproduce it yet!

**Comment by tex** [comment]
Yeah, #18 looks like the same issue I have.
Maybe it is due to version of neovim?
I'll try to prepare some sreenshots to show the problem better.

**Comment by Shougo** [comment]
Please upload the sample C++ file.
And the reproduce ways using it.

**Comment by tex** [comment]
Sorry, no time. I'm closing this issue.
Anyway, it works for me with set noshowmode.
If you are unable to reproduce it then it is probably my configuration or neovim version...

**Comment by Shougo** [comment]
Hm..  OK.
