### ISSUE TITLE
echodoc.vim not works on vim8 and macvim

### ISSUE THREAD

**Issue by jsfaint** [Shougo/echodoc.vim#18]
The latest echodoc.vim in git not works on vim8 and macvim

vim8: v8.0.0046 (win64)
macvim: snapshot-113

echodoc.vim not works for both vim8 and macvim since this commit 7b8b42d40bd384c84e93c38032b2fa2ab5af5749
![image](https://cloud.githubusercontent.com/assets/571829/19755016/07d291de-9c45-11e6-9d62-3cfef3b51ea0.png)
When I press `<c-y>`, nothing showed up.

But this commit [3d80a9aa1a33ad396f24eaecb38f5135bbdc35c5] works fine
![image](https://cloud.githubusercontent.com/assets/571829/19754995/e8c1e1aa-9c44-11e6-9ff2-895e6c0f2f8f.png)

Thanks

**Comment by Shougo** [comment]
OK.  I will test it.
But why does not upload the repdocue ways and minimal vimrc?
I cannot reproduce it.
Of course, both works in my environment.

**Comment by jsfaint** [comment]
@shougo Thanks, maybe there are some issue in my vimrc.
I'll check it later, and provide reproduce way :)

**Comment by Shougo** [comment]
OK.  I wait.

**Comment by jsfaint** [comment]
@shougo with the minimal vimrc, echodoc.vim still can't work on my side, but with commit [3d80a9aa1a33ad396f24eaecb38f5135bbdc35c5], echodoc.vim always works

my macvim is install via brew
```
Built from source on 2016-10-30 at 21:35:45 with: --with-luajit --with-python3
```

The minimal vimrc is here
```
set nocompatible

"Enable filetype plugin
filetype plugin indent on

"Enable syntax highlight
syntax enable

set noshowmode

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugin configuration
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype plugin indent off

if has("win32") || has('win64')
  set rtp+=$VIM/vimfiles/bundle/neobundle.vim/
  call neobundle#begin('$VIM/vimfiles/bundle')
elseif has("unix")
  set rtp+=$HOME/.vim/bundle/neobundle.vim/
  call neobundle#begin('$HOME/.vim/bundle')
endif

"C Family
NeoBundle 'justmao945/vim-clang', {'on_ft': ['c', 'cpp'], 'disabled': !executable('clang')}

"Python
NeoBundle 'davidhalter/jedi-vim', {'on_ft': 'python', 'disabled': !(has('python') || has('python3'))}

"Coding
NeoBundle 'shougo/context_filetype.vim', {'on_i': 1, 'disabled': !has('patch-7.4.774')}
NeoBundle 'shougo/echodoc.vim', {'on_source': 'context_filetype.vim', 'disabled': !has('patch-7.4.774')}

call neobundle#end()

NeoBundleCheck

filetype plugin indent on

"vim-clang
if neobundle#is_installed('vim-clang')
  if neobundle#is_installed('neocomplete.vim')
    let g:clang_auto = 0
  endif

  let g:clang_verbose_pmenu = 1
  let g:clang_format_style = 'webkit'

  if has('patch-7.4.775')
    let g:clang_c_completeopt = 'menuone,noinsert'
    let g:clang_cpp_completeopt = 'menuone,noinsert,preview'
  endif
endif

"echodoc.vim
if neobundle#is_installed('echodoc.vim')
  let g:echodoc_enable_at_startup = 1
endif
```

**Comment by tweekmonster** [comment]
@jsfaint I just tried this with the latest build of Vim and echodoc.vim.  To get completions from vim-jedi, I must press `<c-y>` to get a completion.  But echodoc is not displayed until I type `(`.  This is was the intended effect with the recent changes to support nested argument functions.

Does typing `(` after the completion display echodoc for functions?

Also, it looks like your screenshot shows the completion for a snippet.  Are you saying you want to see the snippet's info in the command line?  If so, this issue is unrelated to the Vim build since the recent change only deals with function signatures.

@Shougo maybe there should be an option to use the old method for echodoc?

**Comment by jsfaint** [comment]
@tweekmonster Thank you! It works for me after type `(`.<br>
My mistake, it's just because the default behavior was changed.

About the snippet you see, I don't know why it show the snippet.
I just press `prin` then `<c-x><c-o>` + `<c-y>`, the message was displayed.

**Comment by tweekmonster** [comment]
> Sorry for waste your time, it's my mistake just because the default behavior was changed.

I don't think it's wasting time 😊   I think your issue is valid because the results have changed drastic.  The plugin is 6 years old, after all.

I noticed that @Shougo reduced the number of evaluated characters to `&columns` (previously hard coded to 1000 chars).  It might be reasonable to fallback and display the first line of the completions if function scanning fails.

**Comment by johnheenan** [comment]
I have got the same problem on another OS. But <c-y> with popup menu open does not fix the problem.

I have a fix. Will fork and request a pull in case there are follow up issues.

**Comment by Shougo** [comment]
@jsfaint Please check the latest echodoc.

**Comment by baopham** [comment]
I'm getting same issue as @jsfaint (with the latest commit f92e942) actually, `c-y` doesn't work. If I go back to commit 3d80a9a, it works well. I'm using [macvim snapshot-121](https://github.com/macvim-dev/macvim/releases/tag/snapshot-121).

**Comment by Shougo** [comment]
@baopham Please read this.  I think it is the feature.

```vim
But echodoc is not displayed until I type (. This is was the intended effect with the recent changes to support nested argument functions.
```

You must input `(` character.

**Comment by baopham** [comment]
Sorry to reply on this thread, let me know if you prefer a new issue.

Here is what I get if I switch to 3d80a9a: (line 44)

![image](https://cloud.githubusercontent.com/assets/783410/21960710/08c5f832-db2f-11e6-99ef-57cc6d36ece2.png)

But if I switch to master and input `(`, I get:

![image](https://cloud.githubusercontent.com/assets/783410/21960724/7f6d9c1a-db2f-11e6-9564-63389352d4c0.png)

Is this expected?

**Comment by Shougo** [comment]
It seems bug.
Please create new issue.

Note:  The reproduce ways is needed.
Please upload the script file and the reproduce way from Vim starting.
