### ISSUE TITLE
Can not make it work with nvim-typescript (deoplete)

### ISSUE THREAD

**Issue by whitecolor** [Shougo/echodoc.vim#23]
Install the plugin it using `dein.vim`, have folling options conserning deoplete and
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#auto_complete_start_length = 1
let g:auto_complete_start_length = 1

let g:echodoc_enable_at_startup=1

set splitbelow
set completeopt+=noselect
set completeopt-=preview
```

Also have:
```
set noshowmode
```

And using `arline.vim`

Deoplete completion works

What else should be done to start it work? I actually don't understand how `echodock` gets data what to display.

**Comment by Shougo** [comment]
echodoc is worked when the candidate is inserted.
