### ISSUE TITLE
echodoc.vim does not display signature when completing a function pointer in C

### ISSUE THREAD

**Issue by maxjc** [Shougo/echodoc.vim#25]
Hi 
I cannot get echodoc.vim to show me the signature of a function pointer in C.
I'm using neovim with deoplete.nvim and deoplete-clang (latest master HEAD)

Here are my options:
``` 
let g:deoplete#enable_at_startup=1
let g:deoplete#file#enable_buffer_path=1
let g:deoplete#disable_auto_complete=1
let g:deoplete#enable_refresh_always=0
let g:deoplete#max_list = 500
let g:deoplete#max_menu_width = 60
let g:deoplete#tag#cache_limit_size = 0
let g:deoplete#auto_complete_start_length = 999
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['tag', 'dictionary', 'member', 'buffer', 'omni', 'around']
set completeopt+=noselect
set cpt-=t
set cpt+=i
```
I am getting the following behavior (this is an incomplete C code to give an example): 

![output](https://cloud.githubusercontent.com/assets/28249525/25651281/1549358a-2f97-11e7-95b5-eaf20515e580.gif)

Please let me know if you need more information or if you suspect something is wrong on my local configuration.
Thank you.

**Comment by Shougo** [comment]
I want to test the behavior.
Please upload the sample.c code.

**Comment by Shougo** [comment]
I have tested it. Reproduced.
It seems not the supported pattern.

**Comment by maxjc** [comment]
I'm still seeing the same behavior after updating. Echodoc doesn't produce any output.
Did you use any specific config parameters ? 
Thank you.

**Comment by Shougo** [comment]
Please comment out `#include <stdio.h>` line.

**Comment by maxjc** [comment]
I commented out `#include <stdio.h>` but I'm still getting the same behavior.

**Comment by Shougo** [comment]
Please update deoplete and echodoc.

**Comment by maxjc** [comment]
I did the update of both deoplete and echodoc, but I am still having the issue.

**Comment by Shougo** [comment]
Really?  I cannot reproduce it.

Please see the screenshot.

![echodoc](https://cloud.githubusercontent.com/assets/41495/26182443/64347790-3bb3-11e7-9f3b-682f31efd53f.png)

**Comment by Shougo** [comment]
Please check your deoplete and echodoc are the latest version.

**Comment by Shougo** [comment]
Minimal vimrc.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set rtp+=~/.cache/dein/repos/github.com/Shougo/echodoc.vim/
set rtp+=~/.cache/dein/repos/github.com/tweekmonster/deoplete-clang2/

set cmdheight=2

let g:echodoc#enable_at_startup = 1

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 150
let g:deoplete#auto_refresh_delay = 1000
let g:deoplete#enable_camel_case = 1

"" set tab complete
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

"" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  deoplete#smart_close_popup()."\<C-h>"
```

If you think don't work, please upload the minimal vimrc and the reproduce ways.

**Comment by maxjc** [comment]
I use deoplete-clang (not deoplete-clang2), I'll try that and let you know.

**Comment by maxjc** [comment]
Ok, I tested it and it does work with deoplete-clang2, it does not work with deoplete-clang.
I'll Investigate on my side to see if I can find something relevant. I've patched deoplete-clang on my own to fix some issues I was seeing, I'll check to be sure it did not cause the problem.

Thank you.

**Comment by Shougo** [comment]
OK
