### ISSUE TITLE
gonvim signature support

### ISSUE THREAD

**Issue by Shougo** [Shougo/echodoc.vim#26]
https://raw.githubusercontent.com/wiki/dzhou121/gonvim/screenshots/signature.gif

I will add the support.

https://github.com/dzhou121/gonvim/issues/12

**Comment by DerWeh** [comment]
Much appreciated. [jedi-vim](https://github.com/davidhalter/jedi-vim) already has a similar feature implemented in vimscript+python. Maybe you can also use some ideas from there.

https://github.com/davidhalter/jedi/raw/master/docs/_screenshots/screenshot_function.png

**Comment by Shougo** [comment]
Implemented.
