### ISSUE TITLE
Function to toggle doc for keyword under cursor

### ISSUE THREAD

**Issue by noh4ck** [Shougo/echodoc.vim#27]
Would it be possible to add a mappable function to toggle/show the echodoc for the keyword under the cursor?

Example: I place the cursor over pr`i`ntln("message") somewhere, then I press `<C-L>` or some other key I've mapped to show the current echodoc.

I know that I can use `<C-K>` most of the time, but I really like the simplicity of echodoc.

**Comment by Shougo** [comment]
You should use the other plugin for it.
echodoc is not the simple documentation tool.
It is only for the completion.
