### ISSUE TITLE
It there a way to get the lastly echoed text?

### ISSUE THREAD

**Issue by liushapku** [Shougo/echodoc.vim#29]
_(I just want to ask a question about this repo and I don't know where to put it. If this is the wrong place, please let me know. Thanks)_
I looked into the source code and didn't found such a function. Is it possible to add one so that the text can be used for other purpose such as text autocompletion?

**Comment by Shougo** [comment]
> I looked into the source code and didn't found such a function. Is it possible to add one so that the text can be used for other purpose such as text autocompletion?

The function is not implemented.  I can add it though.
But what is the advantage?  Please exaplain the example.

**Comment by Shougo** [comment]
Ah, you can get the cached result by `b:echodoc`.

**Comment by liushapku** [comment]
Thank you, Shougo. b:echodoc is enough for me. 
For the usage: Python accepts named arguments and b:echodoc contains the arglist which can be used right there to complete the function call. I then only need to fill the "=value" part for each argument (like completing a snippet).

**Comment by liushapku** [comment]
It seems you removed the `b:echodoc` in the commit `8c2147cd2f2e`. Do you mind to add it back?

I think the following will work in `s:on_event`

    if !empty(echodoc)
      let b:echodoc = echodoc
      call s:display(echodoc, filetype)
    elseif exists('b:echodoc')
      unlet b:echodoc
    endif

Thanks for consideration.

**Comment by Shougo** [comment]
OK.

**Comment by liushapku** [comment]
Thank you very much. You solved big problem.

Shougo <notifications@github.com> 于 2019年3月24日周日 上午11:31写道：
