### ISSUE TITLE
How to show only function at bottom status line

### ISSUE THREAD

**Issue by tuyenpm9** [Shougo/echodoc.vim#32]
I really want the the same way `echodoc` act in readme.md but preview windows keep pop-up and I don't know how to disable it.  
I tried:  
```
set previewheight=3
set winfixheight
```  
set `previewheight=0` doesn't work.   
```
" echodoc settings
set noshowmode
let g:echodoc_enable_at_startup = 1
let g:echodoc_type = 'signature'
```

**Comment by tuyenpm9** [comment]
Oh I see `set completeopt-=preview`.  
Should it add to readme for more clear?

**Comment by tuyenpm9** [comment]
It's just a little blinking when complete function, how to make it fix?

**Comment by Shougo** [comment]
Hm.  I will fix the issue.

**Comment by tuyenpm9** [comment]
@Shougo : That would be great.

**Comment by Shougo** [comment]
Fixed the problem.

**Comment by tuyenpm9** [comment]
Woa, beautiful ~.~
