### ISSUE TITLE
echodoc not working with deoplete-jedi

### ISSUE THREAD

**Issue by LaBatata101** [Shougo/echodoc.vim#33]
# Environment Information
- OS: lubuntu 16.04 32 bit
- Neovim version: 0.2.0
# minimal init.vim
```vim
let g:python3_host_prog = '/usr/bin/python3'
let g:loaded_python_provider = 1

set rtp+=~/.config/nvim/plugged/deoplete.nvim/
set rtp+=~/.config/nvim/plugged/echodoc.vim/

let g:deoplete#enable_at_startup = 1
let g:echodoc#enable_at_sartup = 1
autocmd FileType python setlocal omnifunc=python3complete#Complete
autocmd CompleteDone * silent! pclose!

set noshowmode
```

# Screenshot
![screen](https://imgur.com/Jb4w3PN.png)

**Comment by Shougo** [comment]
deoplete-jedi is not installed in your minimal vimrc.
And I cannot see statusline plugin in your minimal vimrc.
Have you tested the minimal vimrc?

**Comment by Shougo** [comment]
deoplete-jedi and echodoc works for me.

**Comment by Shougo** [comment]
`os.fwalk` cannot be completed by deoplete-jedi.
So it does not work.
echodoc is not magic.
