### ISSUE TITLE
echodoc causing documents with LONG lines to be extremely slow.

### ISSUE THREAD

**Issue by phcerdan** [Shougo/echodoc.vim#36]
I was suffering massive lag when editing files with long lines (see attached)

[compile_commands.log](https://github.com/Shougo/echodoc.vim/files/1537962/compile_commands.log)

After profiling, basically just going to insertmode and try to write a character (it took 20s) echodoc was the one to blame calling `mbprevchar()` way too many times. I have disabled by default, but reporting just in case it is useful.
[profile.log](https://github.com/Shougo/echodoc.vim/files/1537967/profile.log)

Just pointing that `syntax` was off in `nvim`

**Comment by Shougo** [comment]
Reproduced.
I will fix it later.
