### ISSUE TITLE
Doesn't work with Rust/deoplete/racer

### ISSUE THREAD

**Issue by rivertam** [Shougo/echodoc.vim#37]
Hi!

I'm trying to use echodoc with Rust/deoplete/racer, and it's very buggy. Whenever I try to use it, it does nothing until I type the first character of the arguments, at which point it displays `function_name(x` where `x` is the first character of the arguments. Typing anything else doesn't do anything; it just stays there until I exit insert mode.

Here are some images of this happening:

![2018-01-05_22-47-36](https://user-images.githubusercontent.com/4165105/34636263-7fb8d99c-f26b-11e7-8bad-46b7ef0e04d7.png)

![2018-01-05_22-47-57](https://user-images.githubusercontent.com/4165105/34636268-83bafb60-f26b-11e7-8ed5-6631f97eaa93.png)

I also tried with `let g:echodoc#type = "signature"`, which had interesting though also invalid results that I cannot reproduce for some reason. I was seeing type signatures like `() -> -> bool`, which I believe is nonsense for Rust (though the function did return `bool`). When I try to reproduce, I get the same issue as above.

Here's my neovim version information (literally just reinstalled to make sure):

![2018-01-05_22-51-39](https://user-images.githubusercontent.com/4165105/34636270-8bfa1fae-f26b-11e7-9a4e-6581ec94019a.png)

Deoplete is version 4.0 (also just `:PlugUpdate`d)

echodoc is version 1.0

Thanks for a(nother) really cool plugin!

**Comment by Shougo** [comment]
Hm.  The signature is very complicated and not supported well.

The pull request is wellcome.

**Comment by tuyenpm9** [comment]
Need Rust support :)

**Comment by JeanMertz** [comment]
I've run into the same issue.

Here's an example of a (minor) issue that's happening:

Deoplete + LanguageClient shows the signature as expected:

<img width="1085" alt="screenshot 2019-02-14 at 09 47 03" src="https://user-images.githubusercontent.com/383250/52774486-9310c980-303d-11e9-891d-2f42e7c45af1.png">

Echodoc adds an extra `)` at the end (throwing off syntax highlighting):

<img width="1085" alt="screenshot 2019-02-14 at 09 47 14" src="https://user-images.githubusercontent.com/383250/52774533-b5a2e280-303d-11e9-9c8a-07b37691044f.png">

**Comment by Shougo** [comment]
Confirmed.  I will fix it later.

**Comment by Shougo** [comment]
I have fixed Rust errors in the thread.
