### ISSUE TITLE
doesn't work with YCM for python3?

### ISSUE THREAD

**Issue by NewUserHa** [Shougo/echodoc.vim#41]
I typed `prin <tab> <enter> ( ' 123 ' )`

there's nothing dispalying during the tyeping in statebar which I already set cmdheight=2
my c-y is 'already at newest change'

thanks!

**Comment by Shougo** [comment]
Please upload your `v:completed_item` value after completed.

Please upload your minimal init.vim.

If not, I will close your issue.

**Comment by NewUserHa** [comment]
v:completed_item {}
what's minimal init.vim?

**Comment by Shougo** [comment]
> v:completed_item {}

?

Hm.  You should use autocmd to capture it.

`autocmd CompleteDone * echomsg string(v:completed_item)`

> what's minimal init.vim?

Well, have you enabled echodoc?

**Comment by NewUserHa** [comment]
logging.debu..
{'word': 'deb', 'menu':'', 'user_data':'', 'info':'', 'kind':'', 'abbr':''}
oh, I see the `debug(msg, *arg, **kwargs)` only when there's a parenthese after the logging.debug, and it disappear instantly if I type anything inside the paraness even a single quote.
can you keep that until next complete start?

I typed the ( and ' shortly just now.

**Comment by Shougo** [comment]
Hm.  If so, I cannot support YCM.
Sorry.

**Comment by NewUserHa** [comment]
can you keep the output of echodoc.vim until next complete start?

**Comment by Shougo** [comment]
Why it is needed?
It adds the flicker.

**Comment by Shougo** [comment]
I have added `g:echodoc#enable_force_overwrite` option.

**Comment by Shougo** [comment]
> and the c-y in readme.md doesn't work. or just can't work with YCM?

I don't test YCM.  So I don't recommend to use it with echodoc.
deoplete is recommended and tested well.

**Comment by NewUserHa** [comment]
echodoc still works good with jedi-vim.
but echodoc dispaly nothing with YCM since the path 'f1f711b', and `g:echodoc#enable_force_overwrite` seems not working.

**Comment by Shougo** [comment]
Sorry, I cannot support YCM.

**Comment by Shougo** [comment]
I think YCM overwrites the command line.
