### ISSUE TITLE
How can I manually echo doc of the word under the cursor?

### ISSUE THREAD

**Issue by dh-Chen** [Shougo/echodoc.vim#43]

**Comment by Shougo** [comment]
Unfortunately, nothing.
I think you should use other plugin for it.

**Comment by Maltimore** [comment]
@dh-Chen did you find another solution? I just stumbled into this as well.

**Comment by astier** [comment]
Would be a great feature.

**Comment by Shougo** [comment]
It is not possible.
echodoc gets the information from completion candidates.
