### ISSUE TITLE
[Help] How to get echodoc work?

### ISSUE THREAD

**Issue by tuyenpm9** [Shougo/echodoc.vim#44]
Systems: gvim 8.1 / windows 10

For i.e: I have a python file as below:
```
def func1(a, b, c, d)
    a = 10
    b = 0.1
    c = "dfadsf"
    d = "fdklajfa"
    print(a, b, c, d)

func1(a, b, c, d)
```

Problem is that at last line when I try to call `func1` with its arguments, there's no `echodoc` in `statusline` for `func1`.

Steps as follow:
1. type `fu`
2. ctrl-n to trigger completion (I use VimCompletesMe for auto completion)
3. choose `func1` in bottom-down list and then press ctrl-y to trigger echodoc.

But `echodoc` won't be triggered and doesn't echo `func1` prototype.

Related `.vimrc` config:
```
set noshowmode
shortmess=FfilnxtToOcI cmdheight=1 cmdwinheight=7
laststatus=0 statusline=\ 
let g:echodoc_enable_at_startup = 1
let g:echodoc_type = 'echo'
```

**Comment by Shougo** [comment]
You should know echodoc feature.
echodoc just prints the function prototype from the candidate.
If the candidate does not contain the prototype, echodoc does not work.

echodoc is not magic plugin.

I use deoplete+deoplete-jedi for Python.

**Comment by tuyenpm9** [comment]
@Shougo : Can you give a simple example that would trigger echodoc?, I was using echodoc before but recently I couldn't.

**Comment by Shougo** [comment]
Hm...  I don't have the time to teach for you.

Hint:

Please install deoplete+neco-vim
And `call fnamemodify()` in Vim souce code.
You can get it.
