### ISSUE TITLE
RuntimeError: still parsing the file, no completion yet?

### ISSUE THREAD

**Issue by SkqLiao** [Shougo/echodoc.vim#45]
I installed echodoc by vim-plug this afternoon and try to use it in my C++ code.
I installed YCM and I used tab to complete the function name. But nothing appeared at the bottom.
I thought I'd must done something wrong, I tried several times nothing happened until it suddenly appeared "RuntimeError still parsing the file, no completion yet". 
The sentence like this(not exactly), and it disappeared when I try to copy it. 
Did I do something wrong? How to solve it?
I set noshowmode in vimrc and my vim version is 8.1.

**Comment by Shougo** [comment]
Please read #44.

And `RuntimeError: still parsing the file` is YCM's error.
https://github.com/Valloric/YouCompleteMe/issues/2880

I don't use YouCompleteMe.  So I cannot test YCM+echodoc.

I have tested deoplete+echodoc.
