### ISSUE TITLE
Overload args of a function

### ISSUE THREAD

**Issue by tuyenpm9** [Shougo/echodoc.vim#47]
echodoc on `print()` python function, if we try to excess its args: `print(,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,)`, with `noshowmode` and `cmdheight=1`, it causes flick in command bar.

**Comment by Shougo** [comment]
You should use `cmdheight=2`.

**Comment by tuyenpm9** [comment]
I can't, I don't have spaces for two `cmdeight` :)

**Comment by Shougo** [comment]
Unfortunately, it is feature.
