### ISSUE TITLE
Support omni autocompletion?

### ISSUE THREAD

**Issue by tuyenpm9** [Shougo/echodoc.vim#48]
I can make `echodoc` works with typing `print` then type `()` will trigger `echodoc` - in `python` file

But `parser.parse_args` then `()` won't trigger `echodoc`, any suggestions?

`:messages` shows empty in both tries.

**Comment by Shougo** [comment]
https://github.com/Shougo/echodoc.vim/issues/44

Please read it again.
echodoc is not magic plugin.

echodoc just prints the prototype from `v:completed_item`.
