### ISSUE TITLE
Issues with ocaml merlin + deoplete

### ISSUE THREAD

**Issue by rachitnigam** [Shougo/echodoc.vim#52]
I was trying to use echodoc with ocaml merlin deoplete but it doesn't seem to be printing the signatures at all.
From what I can tell from the code, this is probably because of the way ocaml signatures differ from something like vimscript.

Can you point to me a place where I can add a custom parser for ocaml and make it work with echodoc?

Thanks

**Comment by Shougo** [comment]
OK.

You can read `echodoc#util#parse_funcs()` implementation.

The test file is in `test/parse.vim`.
