### ISSUE TITLE
Provide support for patching/cleaning signatures?

### ISSUE THREAD

**Issue by oblitum** [Shougo/echodoc.vim#57]
I'm using [coc.nvim](https://github.com/neoclide/coc.nvim) as my completion engine and it adds a configurable extra char at the end of menu items to indicate they come with snippets from language server.

![recording](https://user-images.githubusercontent.com/1269815/48964264-99d1f800-ef8a-11e8-807d-89dd6eea60ce.gif)

I had to apply [this patch](https://github.com/oblitum/echodoc.vim/commit/a40c785bd6cb18ab4bbcfe07cccb1bab6344f634) to `echodoc.vim` to clean up signature and remove my trailing magic wand char (nf-fa-magic from Nerd Fonts) from echodoc output.

I'm not sure what should be the best solution to this, maybe my local patch already is, but anyways, I'm sharing for ideas.

This was also discussed here: https://github.com/neoclide/coc.nvim/issues/161#issuecomment-438151142.

**Comment by oblitum** [comment]
Just for your information, the reason for the other unrelated change in my patch comes from https://github.com/neoclide/coc.nvim/issues/156#issuecomment-438133920.

**Comment by Shougo** [comment]
Hm.  The non printable characters should be removed.

**Comment by oblitum** [comment]
@Shougo OK, I'm still unsure on that because, even though not good practice, programming languages can support emoji and related.

**Comment by Shougo** [comment]
I have read the code and non printable characters seems removed.

**Comment by oblitum** [comment]
My char is "magic wand" emoji from Nerd Fonts, so it should be printable. My issue is that, it's not part of signature, it's just an snippet indication that completion engine adds to `abbr`:

> The word of complete item doesn't have `~` at end, it could also be resolved if echodoc prefer use word for signature than abbr.

Source: https://github.com/neoclide/coc.nvim/issues/161#issuecomment-438151142

**Comment by oblitum** [comment]
By default `coc.nvim` adds `~` to end of signatures, not magic wand.

**Comment by Shougo** [comment]
I have added `user_data.signature` support for the feature.

coc.nvim can set `word` as `user_data.signature`.

**Comment by oblitum** [comment]
OK thanks, I will check how it behaves now. I think it may not work as I like because signatures with args should be on `abbr` but not on `word` in the end.

**Comment by oblitum** [comment]
Ah, I got it, coc.nvim needs to add the original signature to user_data field, then it will work fine, that's nice.
