### ISSUE TITLE
echo jedi docs in command line

### ISSUE THREAD

**Issue by petobens** [Shougo/echodoc.vim#6]
Consider the following minimal vimrc

    set nocompatible

    let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro/')
    let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

    set runtimepath+=$DOTVIM/bundle/neocomplete
    set runtimepath+=$DOTVIM/bundle/jedi
    set runtimepath+=$DOTVIM/bundle/echodoc

    filetype plugin indent on

    let g:neocomplete#enable_at_startup = 1
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python =
        \ '\%([^. \t]\.\|^\s*@\|^\s*from\s.\+import \|^\s*from \|^\s*import \)\w*'

    augroup py_comp
        au!
        au FileType python setlocal omnifunc=jedi#completions
    augroup END

    let g:echodoc_enable_at_startup	= 1
    set noshowmode
    set cmdheight=2
    set shortmess+=Ic
    set pumheight=15

    let g:jedi#completions_enabled = 0
    let g:jedi#auto_vim_configuration = 0
    if has('python3')
        let g:jedi#force_py_version = 3
    endif

and in a new file (`foo.py`) type `str.` and select the first candidate with `C-n` (i.e `capitalize`). You will see that the preview window opens showing the docs for `S.capitalize()`. 

If I understood correctly the `echodoc` plugin will print the documentation in the command line instead of opening a scratch preview window buffer. It appears it doesn't work in my case. Can this be fixed?

![foo](https://cloud.githubusercontent.com/assets/2583971/5902845/b44c015c-a55c-11e4-98b0-c96d268fd526.gif)

**Comment by Shougo** [comment]
It is feature.   neocomplete does not support echodoc in force omni function(jedi).
You can add jedi extension for echodoc.

**Comment by petobens** [comment]
I have no idea how to add such an extension. Can you show me an example of echodoc extensions? Thanks

**Comment by Shougo** [comment]
https://github.com/Shougo/neocomplete.vim/blob/master/autoload/neocomplete/echodoc.vim

neocomplete can support jedi if the patch is imported in vim.

https://groups.google.com/forum/#!searchin/vim_dev/v$3Acompleted_item/vim_dev/fhGAStSCAMg/q5BIr2EcH4YJ

**Comment by petobens** [comment]
I have upvoted the patch in vim_dev. What I a pity that the features I want require vim patches (that take so long to be merged).

**Comment by petobens** [comment]
@Shougo your patch has been included as patch 774. So now, how can I use jedi with echodocs?

**Comment by Shougo** [comment]
Yes.  You just have to install echodoc and jedi and neocomplete.

**Comment by petobens** [comment]
I'm sorry Shougo but I can't seem to get this to work.  With my vimrc above, echodoc should  print the documentation in the command line? Do I need to change some setting?

**Comment by Shougo** [comment]
The documentation is printed after you inserted candidate.
It is not only selection

**Comment by petobens** [comment]
Ah ok, I get it know. So I think it is not so useful when using jedi-vim since we can have the same behavior with:
```vim
let g:jedi#show_call_signatures = 2
```
