### ISSUE TITLE
How to work with `add(2)(3)` syntax

### ISSUE THREAD

**Issue by aecepoglu** [Shougo/echodoc.vim#61]
Given I have a function that returns a function, how could I have argument completion for it?

For example: `add = a => b => a + b`

When I write this: `add(`
Echodoc will show the first part `add(a: number)`

But when I have write the rest: `add(3)(`
Echodoc still shows `add(a: number)`

Can echodoc do this? If so, how can I add that functionality?
My plugin (`tern`) has already declared the function type as `fn(a: number) -> fn(b: number) -> number`

**Comment by Shougo** [comment]
Sorry.  It is not implemented and hard to support.

**Comment by aecepoglu** [comment]
I wasn't asking for off-the-box support. I can add the functionality myself if you just could just point me the right way.

I know it `skip_chars` in *deoplete* is a start but I haven't looked further.

**Comment by Shougo** [comment]
OK.  Please read `echodoc#util#parse_funcs()` implementation.
The usage is in `test/parse.vim`.
