### ISSUE TITLE
InsertEnter does not trigger echodoc

### ISSUE THREAD

**Issue by timbedard** [Shougo/echodoc.vim#62]
With echodoc enabled and on a function whose signature it knows how to display, entering insert mode does not cause it to display the signature. I would personally prefer to see the function signature immediately, but I imagine there's a reason it doesn't. I see looking through the source that _not_ showing on InsertEnter is by design. Is this purely for performance reasons? Or trying not to step on other plugins' toes?

**Comment by Shougo** [comment]
Please use the latest version.
