### ISSUE TITLE
Cannot get the plugin to work with deoplete

### ISSUE THREAD

**Issue by wallace11** [Shougo/echodoc.vim#64]
I'm pretty sure I'm doing everything correctly:
```vim
call plug#begin('~/.local/share/nvim/plugged')

    " Deoplete (autocompletion); https://github.com/Shougo/deoplete.nvim
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
        let g:deoplete#enable_at_startup = 1
        inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
        inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"

        Plug 'Shougo/neco-syntax'

        Plug 'Shougo/echodoc.vim'
            set noshowmode
            let g:echodoc#enable_at_startup = 1

        Plug 'zchee/deoplete-jedi'

call plug#end()
```

I also tried to remove the `<TAB>` remapping, but it doesn't seem to be it.
What am I missing?

Here's a screenshot of a python file:
![image](https://user-images.githubusercontent.com/5497761/52908109-06bb0c80-32b2-11e9-9dff-fa3272894c42.png)

**Edit:** I just noticed I omitted my nvim version: 
```bash
$ nvim --version                         
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by Shougo** [comment]
It works.  You need to select the completion item and input `(`.

**Comment by wallace11** [comment]
Hi,
I just revisited this, and looking at the readme:

> When you accept a completion for a function with <c-y>, echodoc will display the function signature in the command line and highlight the argument position your cursor is in.

This information is misleading - I could never get it showing **right** after pressing `<c-y>`. The hints will always show after accepting **and** inputting the next possible character.
Maybe it's a good idea to clarify this to prevent further misunderstandings?

**Comment by Shougo** [comment]
> This information is misleading - I could never get it showing **right** after pressing `<c-y>`. The hints will always show after accepting **and** inputting the next possible character.
Maybe it's a good idea to clarify this to prevent further misunderstandings?

The PR is wellcome to improve the documentation.
I don't know what is the better.
