### ISSUE TITLE
Improve README for less experienced users?

### ISSUE THREAD

**Issue by brunobely** [Shougo/echodoc.vim#67]
I'm really loving EchoDoc.  I'm a vim beginner but managed to find what I needed in the docs (in my case, the fact that the plugin isn't enabled at startup by default).  I think future users could benefit from the README being more upfront about that.

Can I add a few things to the README regarding that issue, maybe a couple of other commonly-used options, and installation instructions for a few of the most popular package managers?  That way a user would only have to dig through the help doc if it's something more advanced than basic setup.

**Comment by Shougo** [comment]
If you can improve the documentation, do it.
