### ISSUE TITLE
Echo Doc disappears right after function name completion or selection

### ISSUE THREAD

**Issue by kinowarrior** [Shougo/echodoc.vim#68]
@Shougo - first of all, thanks so much for producing some awesome vim plugins.

My problem here is that echodoc works correctly as I select or complete typing the name of the relevant function. Screenshot below:

![echodoc2](https://user-images.githubusercontent.com/49199497/57122056-27c1d280-6db6-11e9-9e15-fb3d68087a77.gif)

But the moment, I type anything after the function name eg. an open brace `(` etc to fill out the signature of the function, echodoc disappears. I would love to be able to use the feature whereby it keeps the function argument list and highlights my position.

Any ideas? I read the docs a couple of times but didn't notice a specific setting that would be required to enable this (?)  - I do acknowledge my neovim setup is quite "advanced" & i use something like 90 other plugins so maybe some other conflict. Any debugging ideas gratefully received. 

Screenshot below, of my plugin config for echodoc (further above I also specify `cmdheight = 2`. I tried using `set noshowmode` but that didn't appear to have any effect.

Thanks again for the plugins.

![echodoc1](https://user-images.githubusercontent.com/49199497/57122173-ed0c6a00-6db6-11e9-80cb-559e8660a80d.gif)

**Comment by kinowarrior** [comment]
Ok, did a little more testing & reading old issues.

It seems that this is working as expected with python/jedi. 

Screenshot below:

![python-working](https://user-images.githubusercontent.com/49199497/57123567-38297b80-6dbd-11e9-99f2-58f62cd44fca.gif)

So maybe my issue is limited to typescript and working with [nvim-typescript](https://github.com/mhartington/nvim-typescript).

I am going to play with these nvim-typescript settings (as given in docs for that plugin):

![nvim-docs](https://user-images.githubusercontent.com/49199497/57123727-c271df80-6dbd-11e9-9ea7-69fdf8d0d12f.gif)

Report back with findings. Please ignore this issue in interim.

**Comment by Shougo** [comment]
It is not echodoc issues.
Closing.

**Comment by Shougo** [comment]
I think nvim-typescript doesn't support arguments.
