### ISSUE TITLE
minimum configuration to show docs

### ISSUE THREAD

**Issue by bounceme** [Shougo/echodoc.vim#7]
It doesn't seem to work for me,all I want is for the completion doc that normally shows in preview window to always show in the command line(mainly with javascript).this is what i have in my vimrc
```vim
set cmdheight=2
let g:echodoc_enable_at_startup = 1
set completeopt-=preview
Plug 'Shougo/echodoc.vim'
```
Do I need to make a dictionary for every filetype?If so what is an example that I could use?

**Comment by Shougo** [comment]
https://github.com/Shougo/echodoc.vim/issues/6

neocomplete supports echodoc.   So you can use it for echodoc.
But if you want to use echodoc for other omni functions, you should upvote the patch.

**Comment by bounceme** [comment]
That's unfortunate,thank you anyways Shougo!
