### ISSUE TITLE
[Feature request] softwrap long function signatures in floating window mode

### ISSUE THREAD

**Issue by ratheesh** [Shougo/echodoc.vim#71]
Can we softwrap(based on `textwidth`) long function signatures when `echodoc` is configured in floating window mode?

**Comment by Shougo** [comment]
Please request it to @Drakirus.
https://github.com/Shougo/echodoc.vim/pull/70

**Comment by Drakirus** [comment]
I might take a look at this. But not now.

**Comment by ratheesh** [comment]
@Drakirus , Thanks.

Can you please tell me how to disable `colorcolumn` in the floating window? I tried using `nvim_win_set_option` but did not work.

I asking this because I have `colorcolumn` set after column 81. Due to this, the floating window is showing colorcolumn bg color after 80 columns.  I want default bg color to be set to the entire floating window.

**Comment by Drakirus** [comment]
The plug-in sets the `colorcolumn` to false. 
I don't think the issue is related to `colorcolumn`.

**Comment by ratheesh** [comment]
Thank you. I will look forward to this fix.
