### ISSUE TITLE
VIM Popup API

### ISSUE THREAD

**Issue by blayz3r** [Shougo/echodoc.vim#73]
Can Echodoc be adapted to have a floating signature with Vim 8 like https://github.com/Valloric/YouCompleteMe/issues/234#issuecomment-500130951

**Comment by Shougo** [comment]
current echodoc supports neovim floating window, but it doesn't support Vim8 floating API.

**Comment by Shougo** [comment]
I have not the motivation.  You can implement it!

**Comment by tracyone** [comment]
hi， latest vim version has a new option: `completeopt`, which turn preview window into popup window automatically

**Comment by blayz3r** [comment]
> 
> hi， latest vim version has a new option: `completeopt`, which turn preview window into popup window automatically

It's not new, and what does that have to do with the signature?

**Comment by tracyone** [comment]
@blayz3r sorry about it. I mean `completepopup`.  and `completeopt` has a new value `popup`.

We can implement following with `'completeopt` and completepopup` being set correctly.

![photo_2019-08-24 22 46 25](https://user-images.githubusercontent.com/4246425/64072443-ed633600-ccc0-11e9-8834-088dd7722336.jpeg)

**Comment by tracyone** [comment]
precondition is  echodoc.vim must support show vim document in preview window.

**Comment by Shougo** [comment]
completepopup is replace of completeopt preview.
But it is not replace of echodoc.

Because, echodoc can print signature without popup menu.

**Comment by Shougo** [comment]
Fixed by #77

**Comment by blayz3r** [comment]
Thank you!!
