### ISSUE TITLE
Function signatures are hidden by ... 

### ISSUE THREAD

**Issue by tomgeorge** [Shougo/echodoc.vim#74]
First off, thanks for all the great work you've done on neovim!  

Same issue as #5.  That issue recommends setting a neocomplete setting, but as I understand that project is deprecated for deoplete.  I tried setting it in vim myself anyway e.g `:let g#neocomplete#max_keyword_width=500` but that didn't work.  Do you have any suggesstions?

**Comment by Shougo** [comment]
I don't understand.
What auto completion plugin do you use?

**Comment by Shougo** [comment]
max_keyword_width should work in neocomplete.
But not in other auto completion plugins

**Comment by Shougo** [comment]
And this is not echodoc issue.
Closing.

**Comment by tomgeorge** [comment]
I am using languageclient-neovim with deoplete

**Comment by Shougo** [comment]
> I am using languageclient-neovim with deoplete

In deoplete, you must use `max_abbr_width` option instead.

**Comment by tomgeorge** [comment]
Thanks!
