### ISSUE TITLE
Anyway to automatically expand floating window

### ISSUE THREAD

**Issue by Noah11012** [Shougo/echodoc.vim#76]
Before telling what my issue is, I want to thank you for creating this plugin. It's so helpful seeing what the function parameters are without having to constantly go back to the documentation. But there is only problem I would like to know a fix to: when a function has more than three arguments, parameters in the middle are left as trails.

Picture:
![echodoc](https://user-images.githubusercontent.com/26338478/68703436-a7480f80-0558-11ea-8c85-ff1d25124798.png)

**Comment by Shougo** [comment]
What auto completion do you use?
echodoc use candidates as documentation.
So if completion plugin hide arguments, the documentation will be hidden.

**Comment by Shougo** [comment]
> But there is only problem I would like to know a fix to: when a function has more than three arguments, parameters in the middle are left as trails.

So you need to fix/change the auto completion plugin configuration.

**Comment by Noah11012** [comment]
I use Deoplete as the autocompletion plugin.

**Comment by Shougo** [comment]
If you use deoplete,

```vim
" Change the truncate width.
call deoplete#custom#source('_', 'max_abbr_width', 0)
```

**Comment by Noah11012** [comment]
Thanks!
