### ISSUE TITLE
echodoc with eclim for java file

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/echodoc.vim#8]
can we use echodoc to display function paramettre with eclim completion

**Comment by 7belrhalmia** [comment]
for exemple i use eclim for autocompletion in vim when neocomplete show tag complete echodpc work but when it's  a function provided by eclim it dose nothing

**Comment by Shougo** [comment]
https://github.com/Shougo/echodoc.vim/issues/6

**Comment by 7belrhalmia** [comment]
i didn't understand how to add the patch plz explain

**Comment by Shougo** [comment]
This patch is already included in Vim 7.4.775.  Please update your Vim.
