### ISSUE TITLE
wrong trigger time

### ISSUE THREAD

**Issue by bstaint** [Shougo/echodoc.vim#82]
such
```
print()
m["
```
or
```
print()
m["test"] = "
```
will trigger print signature.

**Comment by Shougo** [comment]
Please upload the reproducible instruction.
Your report is not reproducible for me.

If not, I will ignore your issue.

**Comment by Shougo** [comment]
https://github.com/Shougo/echodoc.vim/issues/79#issue-550844559

This report is reproducible.

**Comment by Shougo** [comment]
Another example.
https://github.com/Shougo/echodoc.vim/issues/63#issuecomment-463893338

I will close it if you don't upload instructions.

**Comment by Shougo** [comment]
This is minimal vimrc.

```vim
set rtp+=~/work/echodoc.vim
set rtp+=~/work/deoplete.nvim

let g:deoplete#enable_at_startup = 1
let g:echodoc#enable_at_startup = 1

set cmdheight=2

filetype plugin indent on
syntax enable
```

**Comment by bstaint** [comment]
Sorry, under minimal vimrc:
```
set rtp+=$VIM/vimfiles/plugged/echodoc.vim

let g:echodoc#enable_at_startup = 1

set cmdheight=2

filetype plugin indent on
syntax enable
```

code:
```

print("")
msg["t
```
first line have blank line.

call echodoc#util#get_func_text() will output:
```

print("")
msg["t
```

**Comment by Shougo** [comment]
OK.  I get the reason.
Please wait.

**Comment by Shougo** [comment]
Fixed.
