### ISSUE TITLE
Echodoc doesn't close when cursor leaves function calls

### ISSUE THREAD

**Issue by NovaDev94** [Shougo/echodoc.vim#83]
I couldn't find the behavior of https://github.com/Shougo/echodoc.vim/pull/21 with any of `echo`, `virtual` and `floating` mode.

Example (with `virtual`):
![image](https://user-images.githubusercontent.com/6073918/75829924-0b316500-5de2-11ea-9e04-55b517eaa3ae.png)

Example (with `floating`)
![image](https://user-images.githubusercontent.com/6073918/75830044-50ee2d80-5de2-11ea-998e-a0ea986acd9c.png)

Minimal vimrc
```python
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/echodoc.vim'
Plug 'deoplete-plugins/deoplete-jedi', { 'for': 'python' }

let g:deoplete#enable_at_startup = 1
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = 'virtual'
```

**Comment by Shougo** [comment]
Fixed.
