### ISSUE TITLE
"self" wasn't removed from argument list while writing rust

### ISSUE THREAD

**Issue by chuling** [Shougo/echodoc.vim#86]
"self" wasn't removed from argument list while writing rust. Related issue: <https://github.com/Shougo/echodoc.vim/issues/75>

![image](https://user-images.githubusercontent.com/23468295/78767810-a8715180-79bd-11ea-8ec9-e5f1ec5922ae.png)

![image](https://user-images.githubusercontent.com/23468295/78767819-ad360580-79bd-11ea-9933-17ad81846a21.png)

**Comment by Shougo** [comment]
You need to upload the reproduce-able minimal vimrc and instructions.
If not, I will ignore your issue and close it.

**Comment by Shougo** [comment]
Reproduced.

**Comment by chuling** [comment]
```viml
" --- autocomplete ---
let g:deoplete#enable_at_startup = 1
autocmd cmd_once InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
set completeopt-=preview
" echodoc
let g:echodoc_enable_at_startup = 1
let g:echodoc#type = 'floating'
" lsp
let g:LanguageClient_serverCommands = {
  \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],
  \ 'python': ['/Users/ling/Library/Python/3.7/bin/pyls'],
  \ 'go': ['~/go/bin/gopls'],
  \ 'typescript': ['/Users/ling/opt/npm/bin/typescript-language-server', '--stdio'],
  \ 'cpp': ['/usr/local/Cellar/llvm/10.0.0_1/bin/clangd'],
  \ 'c': ['/usr/local/Cellar/llvm/10.0.0_1/bin/clangd'],
  \ }
autocmd cmd_once BufWritePre *.rs,*.py,*.go,*.ts,*.cc,*.h
  \ :call LanguageClient_textDocument_formatting()
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
let g:LanguageClient_windowLogMessageLevel = 'Error'
```

It was my negligence that minimal vimrc was not provided here, but I don't think that this bug has something to do with vimrc, since <https://github.com/Shougo/echodoc.vim/issues/75> has shown that 
 remove `self` is the expected action.

And thanks for fixing it so quickly.
