### ISSUE TITLE
problem with eclim

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/echodoc.vim#9]
hey first when i use eclim with neocomplete i do have nothing

![screenshot from 2015-07-29 14 02 51](https://cloud.githubusercontent.com/assets/13202562/8958094/a97c1f12-35fa-11e5-8add-3e3872ed28df.png)

but when it's from tag i have echodoc work

![screenshot from 2015-07-29 14 03 11](https://cloud.githubusercontent.com/assets/13202562/8958117/d4f5909c-35fa-11e5-9b18-d20678ff2f45.png)

this my echodocs config
![screenshot from 2015-07-29 13 11 42](https://cloud.githubusercontent.com/assets/13202562/8958984/153676bc-3600-11e5-8520-996435382624.png)

and neocomplete config : 

![screenshot from 2015-07-29 14 43 53](https://cloud.githubusercontent.com/assets/13202562/8959021/4b172ef2-3600-11e5-94b1-e83dfdd9f592.png)

**Comment by 7belrhalmia** [comment]
echodoc work perfectly with jedi  but not with eclim

**Comment by Shougo** [comment]
I think it is feature.
eclim and ternjs does not support Vim's info feature.
