### ISSUE TITLE
disappear after a arg

### ISSUE THREAD

**Issue by zdmgmail** [Shougo/echodoc.vim#92]
https://user-images.githubusercontent.com/50515839/114255244-b994da00-99e6-11eb-8a47-a2ec797cb020.mp4

In video , a function in go has 6 args, but why echodoc disappear after four args?

config:

```
" Or, you could use vim's popup window feature.
let g:echodoc#enable_at_startup = 1
let g:echodoc#type = 'popup'
" To use a custom highlight for the popup window,
" change Pmenu to your highlight group
highlight link EchoDocPopup Pmenu
```

main.go:  https://0x0.st/-Tcf.go

**Comment by Shougo** [comment]
I have added `g:echodoc#max_line_guard` value.  Please increase it.

**Comment by zdmgmail** [comment]
> I have added `g:echodoc#max_line_guard` value. Please increase it.

I add `let g:echodoc#max_line_guard=10` but get same result ...

**Comment by Shougo** [comment]
Really????
Please upload the real example and vimrc.
It must be reproduce-able for all people.
We have not ESP skills.

I cannot reproduce it from your information.

**Comment by Shougo** [comment]
Please compare your report with this.
https://github.com/Shougo/echodoc.vim/issues/86

**Comment by Shougo** [comment]
To test the module, project directory is needed.
Please don't upload main.go only!

> main.go: 0x0.st/-Tcf.go

**Comment by Shougo** [comment]
I will ignore your report until your upload.
