### ISSUE TITLE
Ctags

### ISSUE THREAD

**Issue by 00sapo** [Shougo/echodoc.vim#95]
Hello,
is there a way to use tags for signature help? Universal ctags support this by using the `-S` flag and vim provides it with the `signature` key in the tag element

**Comment by Shougo** [comment]
echodoc gather the information from `v:completed_item`.
It means, you need to complete candidate.

echodoc does not support ctags signature.
To implement to gather tags is possible.  But it is very slow and blocking.
I don't want to implement it.

I think LSP is better than ctags.

**Comment by 00sapo** [comment]
In my experience, ctags is much faster than LSP, and LSP are pretty unusable for large code-bases, while they are superfluous for little code-bases. Moreover, LSP have many issues with virtual environment and similar stuffs.

But I see your point, ctags will be superseded sooner or later. However, I think it is still the best way to cover almost any language with no bloating dependency... If you can point me to a simple example, I could implement that, maybe

**Comment by Shougo** [comment]
> In my experience, ctags is much faster than LSP, and LSP are pretty unusable for large code-bases, while they are superfluous for little code-bases. Moreover, LSP have many issues with virtual environment and similar stuffs.

My main concern is not ctags's speed.
My concern is ctags file parse speed in Vim script.
It is different problem.

For example `deoplete-tag` parses the tag file and returns completion list.
It is better than Vim script parsing.

https://github.com/deoplete-plugins/deoplete-tag

**Comment by 00sapo** [comment]
So you're saying that to get signature help via ctags, the completion source should add the `signature` field to the completion item?

**Comment by Shougo** [comment]
Yes.
