### ISSUE TITLE
Multiline functions in Elixir

### ISSUE THREAD

**Issue by giddie** [Shougo/echodoc.vim#96]
This _may_ apply to other languages, but so far I've only tested it with Elixir:

https://asciinema.org/a/MdiMoT8XxmLP7CuLvgSq55pLM

Basically, the issue is that when writing a function that spans multiple lines,  the "floating" mode function signature obscures text inside the function I'm writing. The ideal solution would be to bump the signature up to sit on the line immediately above the start of the function, rather than always above the line the cursor is on.

**Comment by Shougo** [comment]
I get it.  But it is too too hard to implement.
Because the position information is removed...

**Comment by Shougo** [comment]
I have added it.

**Comment by giddie** [comment]
Brilliant; thanks for looking at this :+1:  There seems to still be some issues with multiple windows:

https://asciinema.org/a/PWX6KfBix0MMu2XoaXO9neXFk

**Comment by Shougo** [comment]
What is the issue?
Please explain it more clearly.
I have not ESP skills.

**Comment by giddie** [comment]
Sorry, I thought it would be clear from the asciinema demo. When there is a split window, the function signature appears to stick to the leftmost split when writing a function in the rightmost split.

**Comment by Shougo** [comment]
I get it.

**Comment by Shougo** [comment]
Fixed.

**Comment by giddie** [comment]
Brilliant! Thanks so much :) Is there any easy way for the signature to remain in line with the function (like it does when the cursor is on the same line as the start of the function), instead of progressing across the screen with the cursor?

**Comment by Shougo** [comment]
Fixed.

**Comment by giddie** [comment]
Perfect! Thanks so much for fixing it so quickly :pray:  :1st_place_medal:
