### ISSUE TITLE
Autocompletion with deoplete.nvim becomes sluggish

### ISSUE THREAD

**Issue by m-zat** [Shougo/echodoc.vim#98]
Hello,

Recently I started observing degraded performance with `deoplete.nvim` when `echodoc.vim` is activated.
Essentially, iterating through the list of completion becomes very slow when the two plugins are active.
The problem is solved by deactivating `echodoc.vim`.

I observed this behavior both using `vim` and `nvim`, even though the delay is shorter with `nvim`.

**Comment by Shougo** [comment]
Please use the latest version.
